#ifndef RCC_CONFIG_H
#define RCC_CONFIG_H

#define AHB_CLK  84000000
#define APB1_CLK 42000000
#define APB2_CLK 84000000

/*Options:
    RCC_CLK_HSI
    RCC_CLK_HSE
    RCC_CLK_PLL
*/
#define RCC_CLOCK_SOURCE RCC_CLK_PLL

/*Options:
    RCC_CLK_HSI
    RCC_CLK_HSE
*/
#define RCC_CLK_PLL_SRC  RCC_CLK_HSE

/*Options:
 RCC_AHB_DIV_1     
 RCC_AHB_DIV_2    
 RCC_AHB_DIV_4     
 RCC_AHB_DIV_8     
 RCC_AHB_DIV_16    
 RCC_AHB_DIV_64    
 RCC_AHB_DIV_128   
 RCC_AHB_DIV_256   
 RCC_AHB_DIV_512    
*/
#define RCC_AHB_PRESCALER RCC_AHB_DIV_1

/*Options:
 RCC_APB1_DIV_1     
 RCC_APB1_DIV_2    
 RCC_APB1_DIV_4     
 RCC_APB1_DIV_8     
 RCC_APB1_DIV_16     
*/
#define RCC_APB1_PRESCALER RCC_APB1_DIV_2
/*Options:
 RCC_APB2_DIV_1     
 RCC_APB2_DIV_2    
 RCC_APB2_DIV_4     
 RCC_APB2_DIV_8     
 RCC_APB2_DIV_16     
*/
#define RCC_APB2_PRESCALER RCC_APB2_DIV_1

/*Options:
192--------432
*/
#define RCC_PLLN_VALUE 168

/*Options:
2------63
*/
#define RCC_PLLM_VALUE 25

/*Options:
 RCC_PLLP_DIV_2
 RCC_PLLP_DIV_4
 RCC_PLLP_DIV_6 
 RCC_PLLP_DIV_8
*/
#define RCC_PLLP_VALUE RCC_PLLP_DIV_2

#endif
